In [1]:
import pandas as pd
import jqdatasdk as jq
jq.auth('18357670235', 'Claire06061')

auth success

In [2]:
prices = pd.read_csv('prices.csv')
flows = pd.read_csv('flows.csv')

In [3]:
prices

,date,code,open,close,high,low,volume,money
0,2017-01-03,000019.XSHE,13.68,13.89,14.17,13.68,7792961.0,1.086515e+08
1,2017-01-04,000019.XSHE,13.92,14.09,14.15,13.83,13162169.0,1.847346e+08
2,2017-01-05,000019.XSHE,14.04,14.25,14.42,13.96,18489374.0,2.631057e+08
3,2017-01-06,000019.XSHE,14.23,14.59,14.87,14.09,32028576.0,4.646525e+08
4,2017-01-09,000019.XSHE,14.38,14.59,14.69,14.28,19918312.0,2.886424e+08
...,...,...,...,...,...,...,...,...
199983,2021-09-24,603919.XSHG,33.64,33.90,34.79,33.49,6850389.0,2.335632e+08
199984,2021-09-27,603919.XSHG,34.30,36.70,37.00,34.27,15582434.0,5.612365e+08
199985,2021-09-28,603919.XSHG,36.80,34.98,36.80,34.15,8237123.0,2.885085e+08
199986,2021-09-29,603919.XSHG,34.41,34.53,35.87,34.21,6646533.0,2.320972e+08
199987,2021-09-30,603919.XSHG,34.05,34.47,35.12,34.01,5165078.0,1.785358e+08

In [4]:
flows

,date,code,change_pct,net_amount_main,net_pct_main,net_amount_xl,net_pct_xl,net_amount_l,net_pct_l,net_amount_m,net_pct_m,net_amount_s,net_pct_s
0,2017-01-03,000019.XSHE,0.93,-62.1200,-0.5700,23.3400,0.2100,-85.4600,-0.7900,-411.7000,-3.7900,473.8300,4.3600
1,2017-01-04,000019.XSHE,1.47,889.4100,4.8100,106.6600,0.5800,782.7600,4.2400,98.7400,0.5300,-988.1500,-5.3500
2,2017-01-05,000019.XSHE,1.15,836.7000,3.1800,335.2200,1.2700,501.4900,1.9100,98.5400,0.3700,-935.2400,-3.5500
3,2017-01-06,000019.XSHE,2.39,2793.0300,6.0100,2136.8300,4.6000,656.2000,1.4100,-297.1400,-0.6400,-2495.8900,-5.3700
4,2017-01-09,000019.XSHE,0.00,-1805.8300,-6.2600,-1710.9400,-5.9300,-94.8800,-0.3300,167.6300,0.5800,1638.1900,5.6800
...,...,...,...,...,...,...,...,...,...,...,...,...,...
193177,2021-09-24,603919.XSHG,0.77,1234.5244,5.2856,187.5591,0.8030,1046.9653,4.4826,-1101.1741,-4.7147,-133.3502,-0.5709
193178,2021-09-27,603919.XSHG,8.26,6473.6944,11.5347,3506.4156,6.2477,2967.2788,5.2870,-2122.3671,-3.7816,-4351.3273,-7.7531
193179,2021-09-28,603919.XSHG,-4.69,-1404.1448,-4.8669,-302.2836,-1.0477,-1101.8612,-3.8192,-632.8935,-2.1937,2037.0382,7.0606
193180,2021-09-29,603919.XSHG,-1.29,-1185.5019,-5.1078,-326.2734,-1.4058,-859.2285,-3.7020,92.0705,0.3967,1093.4315,4.7111
193181,2021-09-30,603919.XSHG,-0.17,-1115.7365,-6.2494,536.0378,3.0024,-1651.7743,-9.2518,-632.6398,-3.5435,1748.3763,9.7929

In [5]:
prices.set_index(['code', 'date'], inplace=True)

In [6]:
flows.set_index(['code', 'date'], inplace=True)

In [7]:
con = pd.concat([prices, flows], axis=1, join='inner')

In [8]:
con

                         open  close   high    low      volume         money  \
code        date
000019.XSHE 2017-01-03  13.68  13.89  14.17  13.68   7792961.0  1.086515e+08
            2017-01-04  13.92  14.09  14.15  13.83  13162169.0  1.847346e+08
            2017-01-05  14.04  14.25  14.42  13.96  18489374.0  2.631057e+08
            2017-01-06  14.23  14.59  14.87  14.09  32028576.0  4.646525e+08
            2017-01-09  14.38  14.59  14.69  14.28  19918312.0  2.886424e+08
...                       ...    ...    ...    ...         ...           ...
603919.XSHG 2021-09-24  33.64  33.90  34.79  33.49   6850389.0  2.335632e+08
            2021-09-27  34.30  36.70  37.00  34.27  15582434.0  5.612365e+08
            2021-09-28  36.80  34.98  36.80  34.15   8237123.0  2.885085e+08
            2021-09-29  34.41  34.53  35.87  34.21   6646533.0  2.320972e+08
            2021-09-30  34.05  34.47  35.12  34.01   5165078.0  1.785358e+08

                        change_pct  net_amount_main  net_pct_main  \
code        date
000019.XSHE 2017-01-03        0.93         -62.1200       -0.5700
            2017-01-04        1.47         889.4100        4.8100
            2017-01-05        1.15         836.7000        3.1800
            2017-01-06        2.39        2793.0300        6.0100
            2017-01-09        0.00       -1805.8300       -6.2600
...                            ...              ...           ...
603919.XSHG 2021-09-24        0.77        1234.5244        5.2856
            2021-09-27        8.26        6473.6944       11.5347
            2021-09-28       -4.69       -1404.1448       -4.8669
            2021-09-29       -1.29       -1185.5019       -5.1078
            2021-09-30       -0.17       -1115.7365       -6.2494

                        net_amount_xl  net_pct_xl  net_amount_l  net_pct_l  \
code        date
000019.XSHE 2017-01-03        23.3400      0.2100      -85.4600    -0.7900
            2017-01-04       106.6600      0.5800      782.7600     4.2400
            2017-01-05       335.2200      1.2700      501.4900     1.9100
            2017-01-06      2136.8300      4.6000      656.2000     1.4100
            2017-01-09     -1710.9400     -5.9300      -94.8800    -0.3300
...                               ...         ...           ...        ...
603919.XSHG 2021-09-24       187.5591      0.8030     1046.9653     4.4826
            2021-09-27      3506.4156      6.2477     2967.2788     5.2870
            2021-09-28      -302.2836     -1.0477    -1101.8612    -3.8192
            2021-09-29      -326.2734     -1.4058     -859.2285    -3.7020
            2021-09-30       536.0378      3.0024    -1651.7743    -9.2518

                        net_amount_m  net_pct_m  net_amount_s  net_pct_s
code        date
000019.XSHE 2017-01-03     -411.7000    -3.7900      473.8300     4.3600
            2017-01-04       98.7400     0.5300     -988.1500    -5.3500
            2017-01-05       98.5400     0.3700     -935.2400    -3.5500
            2017-01-06     -297.1400    -0.6400    -2495.8900    -5.3700
            2017-01-09      167.6300     0.5800     1638.1900     5.6800
...                              ...        ...           ...        ...
603919.XSHG 2021-09-24    -1101.1741    -4.7147     -133.3502    -0.5709
            2021-09-27    -2122.3671    -3.7816    -4351.3273    -7.7531
            2021-09-28     -632.8935    -2.1937     2037.0382     7.0606
            2021-09-29       92.0705     0.3967     1093.4315     4.7111
            2021-09-30     -632.6398    -3.5435     1748.3763     9.7929

[193182 rows x 17 columns]

In [9]:
con.to_csv('concated.csv', index=False)

In [10]:
con

                         open  close   high    low      volume         money  \
code        date
000019.XSHE 2017-01-03  13.68  13.89  14.17  13.68   7792961.0  1.086515e+08
            2017-01-04  13.92  14.09  14.15  13.83  13162169.0  1.847346e+08
            2017-01-05  14.04  14.25  14.42  13.96  18489374.0  2.631057e+08
            2017-01-06  14.23  14.59  14.87  14.09  32028576.0  4.646525e+08
            2017-01-09  14.38  14.59  14.69  14.28  19918312.0  2.886424e+08
...                       ...    ...    ...    ...         ...           ...
603919.XSHG 2021-09-24  33.64  33.90  34.79  33.49   6850389.0  2.335632e+08
            2021-09-27  34.30  36.70  37.00  34.27  15582434.0  5.612365e+08
            2021-09-28  36.80  34.98  36.80  34.15   8237123.0  2.885085e+08
            2021-09-29  34.41  34.53  35.87  34.21   6646533.0  2.320972e+08
            2021-09-30  34.05  34.47  35.12  34.01   5165078.0  1.785358e+08

                        change_pct  net_amount_main  net_pct_main  \
code        date
000019.XSHE 2017-01-03        0.93         -62.1200       -0.5700
            2017-01-04        1.47         889.4100        4.8100
            2017-01-05        1.15         836.7000        3.1800
            2017-01-06        2.39        2793.0300        6.0100
            2017-01-09        0.00       -1805.8300       -6.2600
...                            ...              ...           ...
603919.XSHG 2021-09-24        0.77        1234.5244        5.2856
            2021-09-27        8.26        6473.6944       11.5347
            2021-09-28       -4.69       -1404.1448       -4.8669
            2021-09-29       -1.29       -1185.5019       -5.1078
            2021-09-30       -0.17       -1115.7365       -6.2494

                        net_amount_xl  net_pct_xl  net_amount_l  net_pct_l  \
code        date
000019.XSHE 2017-01-03        23.3400      0.2100      -85.4600    -0.7900
            2017-01-04       106.6600      0.5800      782.7600     4.2400
            2017-01-05       335.2200      1.2700      501.4900     1.9100
            2017-01-06      2136.8300      4.6000      656.2000     1.4100
            2017-01-09     -1710.9400     -5.9300      -94.8800    -0.3300
...                               ...         ...           ...        ...
603919.XSHG 2021-09-24       187.5591      0.8030     1046.9653     4.4826
            2021-09-27      3506.4156      6.2477     2967.2788     5.2870
            2021-09-28      -302.2836     -1.0477    -1101.8612    -3.8192
            2021-09-29      -326.2734     -1.4058     -859.2285    -3.7020
            2021-09-30       536.0378      3.0024    -1651.7743    -9.2518

                        net_amount_m  net_pct_m  net_amount_s  net_pct_s
code        date
000019.XSHE 2017-01-03     -411.7000    -3.7900      473.8300     4.3600
            2017-01-04       98.7400     0.5300     -988.1500    -5.3500
            2017-01-05       98.5400     0.3700     -935.2400    -3.5500
            2017-01-06     -297.1400    -0.6400    -2495.8900    -5.3700
            2017-01-09      167.6300     0.5800     1638.1900     5.6800
...                              ...        ...           ...        ...
603919.XSHG 2021-09-24    -1101.1741    -4.7147     -133.3502    -0.5709
            2021-09-27    -2122.3671    -3.7816    -4351.3273    -7.7531
            2021-09-28     -632.8935    -2.1937     2037.0382     7.0606
            2021-09-29       92.0705     0.3967     1093.4315     4.7111
            2021-09-30     -632.6398    -3.5435     1748.3763     9.7929

[193182 rows x 17 columns]

In [15]:
con2 = pd.DataFrame()
for i in con.columns.values.tolist():
    con2[i] = (con[i] - con[i].mean()) / con[i].std()

In [16]:
con2

                            open     close      high       low    volume  \
code        date
000019.XSHE 2017-01-03 -0.093864 -0.091967 -0.091885 -0.091040 -0.295934
            2017-01-04 -0.091313 -0.089845 -0.092095 -0.089424 -0.070417
            2017-01-05 -0.090038 -0.088147 -0.089269 -0.088024  0.153337
            2017-01-06 -0.088019 -0.084540 -0.084558 -0.086624  0.722010
            2017-01-09 -0.086425 -0.084540 -0.086442 -0.084577  0.213355
...                          ...       ...       ...       ...       ...
603919.XSHG 2021-09-24  0.118246  0.120340  0.123950  0.122349 -0.335524
            2021-09-27  0.125259  0.150048  0.147083  0.130751  0.031239
            2021-09-28  0.151826  0.131799  0.144989  0.129459 -0.277278
            2021-09-29  0.126428  0.127024  0.135255  0.130105 -0.344086
            2021-09-30  0.122603  0.126387  0.127404  0.127951 -0.406310

                           money  change_pct  net_amount_main  net_pct_main  \
code        date
000019.XSHE 2017-01-03 -0.215633    0.317832         0.090077      0.271222
            2017-01-04 -0.098647    0.507556         0.248214      0.871932
            2017-01-05  0.021857    0.395127         0.239454      0.689932
            2017-01-06  0.331757    0.830789         0.564581      1.005919
            2017-01-09  0.061123   -0.008915        -0.199714     -0.364102
...                          ...         ...              ...           ...
603919.XSHG 2021-09-24 -0.023568    0.261617         0.305569      0.925036
            2021-09-27  0.480266    2.893159         1.176279      1.622786
            2021-09-28  0.060917   -1.656703        -0.132957     -0.208554
            2021-09-29 -0.025822   -0.462145        -0.096621     -0.235452
            2021-09-30 -0.108178   -0.068643        -0.085026     -0.362918

                        net_amount_xl  net_pct_xl  net_amount_l  net_pct_l  \
code        date
000019.XSHE 2017-01-03       0.036953    0.150070      0.117132   0.243876
            2017-01-04       0.051964    0.220805      0.418999   0.994568
            2017-01-05       0.093141    0.352717      0.321206   0.646832
            2017-01-06       0.417720    0.989333      0.374996   0.572210
            2017-01-09      -0.275496   -1.023750      0.113857   0.312528
...                               ...         ...           ...        ...
603919.XSHG 2021-09-24       0.066539    0.263438      0.510859   1.030774
            2021-09-27       0.664465    1.304333      1.178523   1.150825
            2021-09-28      -0.021711   -0.090372     -0.236255  -0.208210
            2021-09-29      -0.026033   -0.158832     -0.151896  -0.190719
            2021-09-30       0.129321    0.683910     -0.427452  -1.018987

                        net_amount_m  net_pct_m  net_amount_s  net_pct_s
code        date
000019.XSHE 2017-01-03     -0.107635  -0.523227     -0.049236   0.062145
            2017-01-04      0.045269   0.246002     -0.441430  -1.121547
            2017-01-05      0.045209   0.217512     -0.427237  -0.902119
            2017-01-06     -0.073318   0.037669     -0.845900  -1.123985
            2017-01-09      0.065905   0.254905      0.263117   0.223059
...                              ...        ...           ...        ...
603919.XSHG 2021-09-24     -0.314168  -0.687881     -0.212120  -0.538953
            2021-09-27     -0.620068  -0.521731     -1.343644  -1.414495
            2021-09-28     -0.173894  -0.238986      0.370113   0.391360
            2021-09-29      0.043271   0.222266      0.116979   0.104946
            2021-09-30     -0.173818  -0.479335      0.292676   0.724440

[193182 rows x 17 columns]

In [18]:
con2.to_csv('con2.csv')