In [14]:
import pandas as pd
import numpy as np

In [4]:
db = pd.read_excel('Superfam_Databasewku.xlsx', sheet_name=' Dealer Satisfaction')
db

,Dealer Satisfaction,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Survey Scale:,0.0,1.0,2.0,3.0,4.0,5.0,Sample
2,North America,0.0,1.0,2.0,3.0,4.0,5.0,Size
3,2010,1.0,0.0,2.0,14.0,22.0,11.0,50
4,2011,0.0,0.0,2.0,14.0,20.0,14.0,50
5,2012,1.0,1.0,1.0,8.0,34.0,15.0,60
6,2013,1.0,2.0,6.0,12.0,34.0,45.0,100
7,2014,2.0,3.0,5.0,15.0,44.0,56.0,125
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
9,South America,NaN,NaN,NaN,NaN,NaN,NaN,
10,2010,0.0,0.0,0.0,2.0,6.0,2.0,10
11,2011,0.0,0.0,0.0,2.0,6.0,2.0,10
12,2012,0.0,0.0,1.0,4.0,11.0,14.0,30
13,2013,0.0,1.0,1.0,3.0,12.0,33.0,50
14,2014,1.0,1.0,2.0,4.0,22.0,60.0,90
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
16,Europe,NaN,NaN,NaN,NaN,NaN,NaN,
17,2010,0.0,0.0,1.0,3.0,7.0,4.0,15
18,2011,0.0,0.0,1.0,2.0,8.0,4.0,15
19,2012,0.0,0.0,1.0,2.0,15.0,7.0,25
20,2013,0.0,0.0,1.0,2.0,21.0,6.0,30
21,2014,0.0,0.0,1.0,4.0,17.0,8.0,30
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
23,Pacific Rim,NaN,NaN,NaN,NaN,NaN,NaN,
24,2010,0.0,0.0,1.0,2.0,2.0,0.0,5
25,2011,0.0,0.0,1.0,1.0,3.0,0.0,5
26,2012,0.0,0.0,1.0,1.0,3.0,1.0,6
27,2013,0.0,0.0,0.0,2.0,5.0,3.0,10
28,2014,0.0,0.0,1.0,2.0,7.0,2.0,12
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
30,China,NaN,NaN,NaN,NaN,NaN,NaN,
31,2012,0.0,0.0,0.0,1.0,0.0,0.0,1
32,2013,0.0,0.0,1.0,4.0,2.0,0.0,7
33,2014,0.0,0.0,1.0,5.0,8.0,2.0,16

In [5]:
db.columns = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [6]:
db

                a    b    c    d     e     f     g        h
0             NaN  NaN  NaN  NaN   NaN   NaN   NaN      NaN
1   Survey Scale:  0.0  1.0  2.0   3.0   4.0   5.0  Sample
2   North America  0.0  1.0  2.0   3.0   4.0   5.0     Size
3            2010  1.0  0.0  2.0  14.0  22.0  11.0       50
4            2011  0.0  0.0  2.0  14.0  20.0  14.0       50
5            2012  1.0  1.0  1.0   8.0  34.0  15.0       60
6            2013  1.0  2.0  6.0  12.0  34.0  45.0      100
7            2014  2.0  3.0  5.0  15.0  44.0  56.0      125
8             NaN  NaN  NaN  NaN   NaN   NaN   NaN
9   South America  NaN  NaN  NaN   NaN   NaN   NaN
10           2010  0.0  0.0  0.0   2.0   6.0   2.0       10
11           2011  0.0  0.0  0.0   2.0   6.0   2.0       10
12           2012  0.0  0.0  1.0   4.0  11.0  14.0       30
13           2013  0.0  1.0  1.0   3.0  12.0  33.0       50
14           2014  1.0  1.0  2.0   4.0  22.0  60.0       90
15            NaN  NaN  NaN  NaN   NaN   NaN   NaN
16         Europe  NaN  NaN  NaN   NaN   NaN   NaN
17           2010  0.0  0.0  1.0   3.0   7.0   4.0       15
18           2011  0.0  0.0  1.0   2.0   8.0   4.0       15
19           2012  0.0  0.0  1.0   2.0  15.0   7.0       25
20           2013  0.0  0.0  1.0   2.0  21.0   6.0       30
21           2014  0.0  0.0  1.0   4.0  17.0   8.0       30
22            NaN  NaN  NaN  NaN   NaN   NaN   NaN
23    Pacific Rim  NaN  NaN  NaN   NaN   NaN   NaN
24           2010  0.0  0.0  1.0   2.0   2.0   0.0        5
25           2011  0.0  0.0  1.0   1.0   3.0   0.0        5
26           2012  0.0  0.0  1.0   1.0   3.0   1.0        6
27           2013  0.0  0.0  0.0   2.0   5.0   3.0       10
28           2014  0.0  0.0  1.0   2.0   7.0   2.0       12
29            NaN  NaN  NaN  NaN   NaN   NaN   NaN
30          China  NaN  NaN  NaN   NaN   NaN   NaN
31           2012  0.0  0.0  0.0   1.0   0.0   0.0        1
32           2013  0.0  0.0  1.0   4.0   2.0   0.0        7
33           2014  0.0  0.0  1.0   5.0   8.0   2.0       16

In [10]:
db = db.dropna()
db

                a    b    c    d     e     f     g        h
1   Survey Scale:  0.0  1.0  2.0   3.0   4.0   5.0  Sample
2   North America  0.0  1.0  2.0   3.0   4.0   5.0     Size
3            2010  1.0  0.0  2.0  14.0  22.0  11.0       50
4            2011  0.0  0.0  2.0  14.0  20.0  14.0       50
5            2012  1.0  1.0  1.0   8.0  34.0  15.0       60
6            2013  1.0  2.0  6.0  12.0  34.0  45.0      100
7            2014  2.0  3.0  5.0  15.0  44.0  56.0      125
10           2010  0.0  0.0  0.0   2.0   6.0   2.0       10
11           2011  0.0  0.0  0.0   2.0   6.0   2.0       10
12           2012  0.0  0.0  1.0   4.0  11.0  14.0       30
13           2013  0.0  1.0  1.0   3.0  12.0  33.0       50
14           2014  1.0  1.0  2.0   4.0  22.0  60.0       90
17           2010  0.0  0.0  1.0   3.0   7.0   4.0       15
18           2011  0.0  0.0  1.0   2.0   8.0   4.0       15
19           2012  0.0  0.0  1.0   2.0  15.0   7.0       25
20           2013  0.0  0.0  1.0   2.0  21.0   6.0       30
21           2014  0.0  0.0  1.0   4.0  17.0   8.0       30
24           2010  0.0  0.0  1.0   2.0   2.0   0.0        5
25           2011  0.0  0.0  1.0   1.0   3.0   0.0        5
26           2012  0.0  0.0  1.0   1.0   3.0   1.0        6
27           2013  0.0  0.0  0.0   2.0   5.0   3.0       10
28           2014  0.0  0.0  1.0   2.0   7.0   2.0       12
31           2012  0.0  0.0  0.0   1.0   0.0   0.0        1
32           2013  0.0  0.0  1.0   4.0   2.0   0.0        7
33           2014  0.0  0.0  1.0   5.0   8.0   2.0       16

In [11]:
db = db.drop(index=[1, 2])
db

       a    b    c    d     e     f     g    h
3   2010  1.0  0.0  2.0  14.0  22.0  11.0   50
4   2011  0.0  0.0  2.0  14.0  20.0  14.0   50
5   2012  1.0  1.0  1.0   8.0  34.0  15.0   60
6   2013  1.0  2.0  6.0  12.0  34.0  45.0  100
7   2014  2.0  3.0  5.0  15.0  44.0  56.0  125
10  2010  0.0  0.0  0.0   2.0   6.0   2.0   10
11  2011  0.0  0.0  0.0   2.0   6.0   2.0   10
12  2012  0.0  0.0  1.0   4.0  11.0  14.0   30
13  2013  0.0  1.0  1.0   3.0  12.0  33.0   50
14  2014  1.0  1.0  2.0   4.0  22.0  60.0   90
17  2010  0.0  0.0  1.0   3.0   7.0   4.0   15
18  2011  0.0  0.0  1.0   2.0   8.0   4.0   15
19  2012  0.0  0.0  1.0   2.0  15.0   7.0   25
20  2013  0.0  0.0  1.0   2.0  21.0   6.0   30
21  2014  0.0  0.0  1.0   4.0  17.0   8.0   30
24  2010  0.0  0.0  1.0   2.0   2.0   0.0    5
25  2011  0.0  0.0  1.0   1.0   3.0   0.0    5
26  2012  0.0  0.0  1.0   1.0   3.0   1.0    6
27  2013  0.0  0.0  0.0   2.0   5.0   3.0   10
28  2014  0.0  0.0  1.0   2.0   7.0   2.0   12
31  2012  0.0  0.0  0.0   1.0   0.0   0.0    1
32  2013  0.0  0.0  1.0   4.0   2.0   0.0    7
33  2014  0.0  0.0  1.0   5.0   8.0   2.0   16

In [12]:
db['i'] = (db['b'] *0 + db['c']*1 + db['d']*2 + db['e']*3 + db['f']*4 + db['g']*5) / db['h']

In [13]:
db

       a    b    c    d     e     f     g    h         i
3   2010  1.0  0.0  2.0  14.0  22.0  11.0   50      3.78
4   2011  0.0  0.0  2.0  14.0  20.0  14.0   50      3.92
5   2012  1.0  1.0  1.0   8.0  34.0  15.0   60  3.966667
6   2013  1.0  2.0  6.0  12.0  34.0  45.0  100      4.11
7   2014  2.0  3.0  5.0  15.0  44.0  56.0  125     4.112
10  2010  0.0  0.0  0.0   2.0   6.0   2.0   10       4.0
11  2011  0.0  0.0  0.0   2.0   6.0   2.0   10       4.0
12  2012  0.0  0.0  1.0   4.0  11.0  14.0   30  4.266667
13  2013  0.0  1.0  1.0   3.0  12.0  33.0   50       4.5
14  2014  1.0  1.0  2.0   4.0  22.0  60.0   90       4.5
17  2010  0.0  0.0  1.0   3.0   7.0   4.0   15  3.933333
18  2011  0.0  0.0  1.0   2.0   8.0   4.0   15       4.0
19  2012  0.0  0.0  1.0   2.0  15.0   7.0   25      4.12
20  2013  0.0  0.0  1.0   2.0  21.0   6.0   30  4.066667
21  2014  0.0  0.0  1.0   4.0  17.0   8.0   30  4.066667
24  2010  0.0  0.0  1.0   2.0   2.0   0.0    5       3.2
25  2011  0.0  0.0  1.0   1.0   3.0   0.0    5       3.4
26  2012  0.0  0.0  1.0   1.0   3.0   1.0    6  3.666667
27  2013  0.0  0.0  0.0   2.0   5.0   3.0   10       4.1
28  2014  0.0  0.0  1.0   2.0   7.0   2.0   12  3.833333
31  2012  0.0  0.0  0.0   1.0   0.0   0.0    1       3.0
32  2013  0.0  0.0  1.0   4.0   2.0   0.0    7  3.142857
33  2014  0.0  0.0  1.0   5.0   8.0   2.0   16    3.6875

In [18]:
db['k'] = ((
    (0 - db['i'])**2 * db['b'] + \
    (1 - db['i'])**2 * db['c'] + \
    (2 - db['i'])**2 * db['d'] + \
    (3 - db['i'])**2 * db['e'] + \
    (4 - db['i'])**2 * db['f'] + \
    (5 - db['i'])**2 * db['g']  \
) / db['h']) ** (1/2)
db

       a    b    c    d     e     f     g    h         i         k
3   2010  1.0  0.0  2.0  14.0  22.0  11.0   50      3.78  0.965194
4   2011  0.0  0.0  2.0  14.0  20.0  14.0   50      3.92  0.844748
5   2012  1.0  1.0  1.0   8.0  34.0  15.0   60  3.966667  0.930352
6   2013  1.0  2.0  6.0  12.0  34.0  45.0  100      4.11  1.066724
7   2014  2.0  3.0  5.0  15.0  44.0  56.0  125     4.112  1.089705
10  2010  0.0  0.0  0.0   2.0   6.0   2.0   10       4.0  0.632456
11  2011  0.0  0.0  0.0   2.0   6.0   2.0   10       4.0  0.632456
12  2012  0.0  0.0  1.0   4.0  11.0  14.0   30  4.266667   0.81377
13  2013  0.0  1.0  1.0   3.0  12.0  33.0   50       4.5    0.8544
14  2014  1.0  1.0  2.0   4.0  22.0  60.0   90       4.5  0.909823
17  2010  0.0  0.0  1.0   3.0   7.0   4.0   15  3.933333   0.85375
18  2011  0.0  0.0  1.0   2.0   8.0   4.0   15       4.0  0.816497
19  2012  0.0  0.0  1.0   2.0  15.0   7.0   25      4.12  0.711056
20  2013  0.0  0.0  1.0   2.0  21.0   6.0   30  4.066667  0.628932
21  2014  0.0  0.0  1.0   4.0  17.0   8.0   30  4.066667  0.727247
24  2010  0.0  0.0  1.0   2.0   2.0   0.0    5       3.2  0.748331
25  2011  0.0  0.0  1.0   1.0   3.0   0.0    5       3.4       0.8
26  2012  0.0  0.0  1.0   1.0   3.0   1.0    6  3.666667  0.942809
27  2013  0.0  0.0  0.0   2.0   5.0   3.0   10       4.1       0.7
28  2014  0.0  0.0  1.0   2.0   7.0   2.0   12  3.833333  0.799305
31  2012  0.0  0.0  0.0   1.0   0.0   0.0    1       3.0       0.0
32  2013  0.0  0.0  1.0   4.0   2.0   0.0    7  3.142857  0.638877
33  2014  0.0  0.0  1.0   5.0   8.0   2.0   16    3.6875  0.768013